[project]
name = "logging-best-practices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.4.0",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.1",
    "rich>=14.2.0",
    "ruff>=0.14.4",
]
